# .github/actions/build-cosmic/action.yml
name: 'Build COSMIC Package'
description: 'Common build steps for COSMIC components'
inputs:
  app_name:
    description: 'Name of the application (e.g., cosmic-files)'
    required: true
  repository:
    description: 'Repository to clone'
    required: true
  ref:
    description: 'Branch or tag'
    required: true
  cargo_patch:
    description: 'Shell commands to patch Cargo.toml (optional)'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Check out app code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0

    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: 'build'

    - name: Install build tools
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper equivs

    - name: Overwrite and install package build dependencies
      shell: bash
      run: |
        cp build/debian/${{ inputs.app_name }}/{changelog,control,rules} debian/
        sudo mk-build-deps -i -t "apt-get -o Debug::pkgProblemResolver=yes -y" debian/control

    - name: Rust Cache
      uses: swatinem/rust-cache@v2

    - name: Patch Cargo.toml
      if: ${{ inputs.cargo_patch != '' }}
      shell: bash
      run: |
        ${{ inputs.cargo_patch }}
        # オンラインで依存関係を更新
        cargo update libcosmic

    - name: Build package using debuild
      shell: bash
      run: |
        # VENDOR=0 を指定して、debian/rules 内のクリーン・展開処理をスキップさせる
        # これにより通常の cargo build が走り、~/.cargo/registry や target が再利用される
        export VENDOR=0
        
        # キャッシュの場所を debuild 内部に教える
        export CARGO_TARGET_DIR=$(pwd)/target
        export CARGO_HOME=$HOME/.cargo
        
        debuild \
          -e PATH=$PATH \
          -e VENDOR=$VENDOR \
          -e CARGO_TARGET_DIR=$CARGO_TARGET_DIR \
          -e CARGO_HOME=$CARGO_HOME \
          -us -uc -b -j$(nproc)

    - name: Prepare Artifacts
      shell: bash
      run: |
        mkdir -p dist
        mv *.deb *.changes *.buildinfo dist/ 2>/dev/null || true
