# .github/actions/build-rpm/action.yml
name: "Build COSMIC Package"
description: "Common build steps for COSMIC components"
inputs:
  app_name:
    required: true
  repository:
    required: true
  ref:
    required: true
  cargo_patch:
    required: false
    default: ""
  arch:
    description: "Target architecture (amd64 or arm64)"
    required: true
    default: "amd64"

runs:
  using: "composite"
  steps:
    - name: Check out app code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        fetch-depth: 0

    - name: Check out repository
      uses: actions/checkout@v4
      with:
        path: "build"

    - name: Install System Dependencies
      shell: bash
      run: |
        # EPEL 10 の導入
        dnf install -y epel-release
        # EL10では CRB の有効化方法が標準化されています
        dnf config-manager --set-enabled crb || dnf install -y 'dnf-command(config-manager)' && dnf config-manager --set-enabled crb
        # just を含む全依存関係を RPM でインストール
        dnf install -y \
          rpm-build \
          pkgconfig \
          gcc-c++ \
          cargo \
          rust \
          just \
          glib2-devel \
          libxkbcommon-devel \
          cmake \
          freetype-devel \
          fontconfig-devel \
          wayland-devel \
          libinput-devel \
          libxkbcommon-x11-devel

    - name: Patch Cargo.toml
      if: ${{ inputs.cargo_patch != '' }}
      shell: bash
      run: |
        ${{ inputs.cargo_patch }}
        cp build/${{ inputs.app_name }}/Cargo.lock . || true

    - name: Rust Cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: .
        # アーキテクチャごとにキャッシュを分ける
        key: ${{ inputs.app_name }}-${{ inputs.arch }}
        # rpmbuildが使用する可能性のある場所をすべて網羅する
        cache-directories: |
          ~/.cargo/registry
          ~/.cargo/git
          ./target

    - name: Prepare Sources
      shell: bash
      run: |
        mkdir -p $GITHUB_WORKSPACE/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}

        # RPMビルド用のディレクトリ構造を作成して固める
        mkdir -p ../${{ inputs.app_name }}-ime-0.1.0
        cp -r . ../${{ inputs.app_name }}-ime-0.1.0/
        cd ..
        tar -czf $GITHUB_WORKSPACE/rpmbuild/SOURCES/${{ inputs.app_name }}-ime-0.1.0.tar.gz ${{ inputs.app_name }}-ime-0.1.0/

    - name: Execute Build (Out of RPM)
      shell: bash
      run: |
        export CARGO_TARGET_DIR=$(pwd)/target
        export CARGO_HOME=$HOME/.cargo

        # ここでビルドを行う。パスは常に ${{ github.workspace }}
        just build-release

    - name: Execute rpmbuild (Packaging only)
      shell: bash
      run: |
        export CARGO_TARGET_DIR=$(pwd)/target

        # %_builddir を現在のワークスペースに強制することで、
        # rpmbuild が ./target/release 内のバイナリを見つけられるようにします
        rpmbuild -bb build/${{ inputs.app_name }}/rpm/${{ inputs.app_name }}.spec \
          --define "cargo_target_dir $CARGO_TARGET_DIR"

    - name: Prepare Artifacts
      shell: bash
      run: |
        mkdir -p dist
        # 拡張子が異なる場合を考慮してコピー
        mv $GITHUB_WORKSPACE/rpmbuild/RPMS/*/*.rpm dist/
